### ISSUE TITLE
Please consider moving it under Processing

### ISSUE THREAD

**Issue by pcav** [aaschwanden/LinearTheoryOrographicPrecipitation#1]
You'll save coding the interface, and the user will be able to integrate this into more complex workflows, having iterations, and much more.
Ask @volaya for howto, or have a look to other Processing plugins.

**Comment by aaschwanden** [comment]
Thanks. 
I've already gone through all the hoops learning how to create a GUI, so I basically would have to start from scratch again to write a plugin under Processing. I've quickly tried to make a dummy processing plugin using the plugin builder. This seems to be less straightforward, the `make deploy` target tries to copy the files under .qgis2/python/plugins not processing and fails.
If you think its worth the effort, I will dive deeper into the matter.

**Comment by pcav** [comment]
Converting it to Processing is very easy. If necessary, you can also keep it in both versions (see QuickOSM and Lecos for examples).
Please ask on qgis-dev and @volaya may provide you hints on how to do it. I think an howto may also be sitting somewhere.

**Comment by ckhroulev** [comment]
The current version is implemented as *two* Processing algorithms: one provides the model itself and the second one generates the DEM that can be used for testing.

**Comment by pcav** [comment]
Thanks for this.
