### ISSUE TITLE
error with some DEMs

### ISSUE THREAD

**Issue by dschneiderch** [aaschwanden/LinearTheoryOrographicPrecipitation#2]
I'm getting an error for some DEMs but not others when trying to run the model. Specifically, both are in the same albers conic equal area projection and 1 is a subset of the other.

I've attached the two dems. 
elev_tropicalAndes_albers.tif is the larger domain and runs fine. elev_tropicalAndes_subsetNorth_alberts.tif is the smaller domain in the image:

![image](https://user-images.githubusercontent.com/7461221/30105230-4e720d04-92f8-11e7-9c14-326d466cee5e.png)

 and gives the following error:

```
2017-09-06T11:20:07	1	Traceback (most recent call last):
			  File "/Users/dosc3612/.qgis2/python/plugins/LinearTheoryOrographicPrecipitation/lt_model_dialog.py", line 374, in run
			    saveRaster(outFileName, geoTrans, proj4, OP.P)
			  File "/Users/dosc3612/.qgis2/python/plugins/LinearTheoryOrographicPrecipitation/lt_model_dialog.py", line 180, in saveRaster
			    outRaster.SetGeoTransform(geoTrans)
			AttributeError: 'NoneType' object has no attribute 'SetGeoTransform'
```
	
Any suggestions? Thanks!	

[Archive.zip](https://github.com/aaschwanden/LinearTheoryOrographicPrecipitation/files/1280575/Archive.zip)

**Comment by aaschwanden** [comment]
I can confirm the issue, both when running the plugin but also when running a standalone code.

Both files have valid projection information, but the orographic precip algorithm returns an empty array so something with the fourier transform may go wrong.

My first guess is that is has to do with the domain size since it's the (small) subset file that fails. I will need some more time to dig into it.

**Comment by aaschwanden** [comment]
The issues was related to padding which was calculated from the grid size. For small grids the resulting padding was wrong.

I've fixed it by using a constant value of 250 grid points.

A later version of the plugin should have the padding value as a user-configurable parameter.

I've uploaded a new version of the plugin. Could you give this a try?

**Comment by dschneiderch** [comment]
The plugin runs now although the results are not very appealing.  In particular there is a severe edge effect at the limits of the real elevation.  
![screen shot 2017-09-08 at 10 58 19](https://user-images.githubusercontent.com/7461221/30204202-d68ba172-9484-11e7-8c74-8e82791c024b.png)

**Comment by aaschwanden** [comment]
This is neither a feature nor a bug.

The orographic precipitation model is a simplifaction of the actual model physics. To avoid boundary effects from the Fourier transforms, careful preprocessing of the DEM is essential. Consider using a larger domain than the subset, especially in the main wind direction. If you extend the DEM enough and fill the extended areas with 0's, the boundary effects should go away.
